### PR TITLE
Program page styling

### PR DESCRIPTION
**Pull request by pedromsfernandes**
Because of the data we currently have, I recommend you use the tab for the second day to check out how the schedule looks. Looking forward to your feedback!

### CODE REVIEW

**Comment by smbea** [comment]
Could you just make the font size a bit smaller overall? More like this:
Screenshot 2019-09-29 at 18 24 20

Also, I don't think this is supposed to be like this:
Screenshot 2019-09-29 at 18 23 21

**Comment by pedromsfernandes** [comment]
I'll work on the font sizing as soon as I can. As for the visit bug, the problem is since we don't have a visit template yet, I had to declare it as such in the markdown file and if I didn't supply the speakers attribute the build would fail. Basically, when the visit component is done, the file won't have a speakers attribute and it won't appear on the program page.

**Comment by smbea** [comment]
Besides the "Company Visits" part it looks good

**Comment by tiagofragoso** [comment]
The preview is throwing errors and not rendering. Please look into it.
I'd really like to have this shipped by the end of the week.

**Comment by pedromsfernandes** [comment]
> The preview is throwing errors and not rendering. Please look into it.

Seems like my sloppy self made a mistake while calculating the default date for the program nav, which threw an error and thus stopped the ProgramPage component from rendering. Should be fixed now!

**Pull request merged**
